### ISSUE TITLE
Error: invalid call of non-function (int)

### ISSUE THREAD

**Issue by TaylorWh0** [mackorone/tidbyt-pokedex#2]
Hello, 

I am very new to this, so I apologize in advance if this error is due to my own ignorance. I attempted to follow your directions exactly and I get an error. "Error: invalid call of non-function (int)" 

Here is a screenshot:
![Error](https://user-images.githubusercontent.com/96747445/147510743-8631e591-efa3-4c5b-87c0-d4ae5eb3d1a3.png)
Any help would be great,

Thank you

**Comment by mackorone** [comment]
Thanks for reporting! The code suffered from bit rot. Here's the fix: 2c0f091d0b5ff69e8a98c6fc4b70610ea6431aa1.
